/**
 * WP5 Slice 5-F — ADR 0021 leaf-split acceptance proofs.
 *
 * Covers the binding refinements N3 (closed compatibility surface and binding
 * identity), N4 (frozen pre-split canonical/fingerprint vectors), N5
 * (deterministic import-graph classification and cycle audit), N6 (raw
 * Node/`tsx` child-process proof), and N8 (single virtual-canvas constant
 * definition + store/leaf identity).
 *
 * The expected canonical strings and fingerprints in `wp5f-normalized-vectors.ts`
 * were captured from the passing pre-split implementation and are never
 * regenerated by the implementation under test.
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

import type { ArtworkResponseDto, CreateArtworkDto } from '@/lib/api/types.gen';
import { snapshotToCreateDto } from '@/lib/artwork/artworkSerialization';
import { generateCrosswordLayout } from '@/lib/artwork/crosswordEngine/layout';
import { CANVAS_LAYOUT_ID as leafId } from '@/lib/artwork/virtualCanvasLayout';
import {
  canonicalizeNormalizedMeaning,
  extractRawCrosswordSemanticPayload,
  fingerprintNormalizedMeaning,
  normalizeArtworkProductMeaning,
  NormalizedMeaningUnusableError,
  type NormalizedArtworkMeaningV1,
  type NormalizedLayerMeaningV1,
  type NormalizedLayoutMeaningV1,
  type RawCrosswordSemanticPayloadV1,
} from '@/lib/artwork/verification/normalizedMeaningCore';
import { normalizeArtworkResponseMeaning } from '@/lib/artwork/verification/normalizedMeaningResponse';
import { createDefaultArtworkCrosswordLayer } from '@/stores/artwork/crosswordLayerSlice';
import { createDefaultArtworkImageLayer } from '@/stores/artwork/imageLayer';
import { createDefaultArtworkTextLayer } from '@/stores/artwork/textLayerSlice';
import type {
  ArtworkEditorSnapshot,
  ArtworkLayoutItem,
  ArtworkPersistedLayer,
} from '@/stores/artworkEditorStore';
import {
  CANVAS_LAYOUT_ID,
  CANVAS_LAYOUT_ID as storeId,
  DEFAULT_LAYOUT_BACKGROUND,
} from '@/stores/artworkEditorStore';

import {
  EQUAL_Z_CANONICAL,
  EQUAL_Z_FINGERPRINT,
  MIXED_CANONICAL,
  MIXED_FINGERPRINT,
  NEG_ZERO_CANONICAL,
  NEG_ZERO_FINGERPRINT,
  RAW_CROSSWORD_FINGERPRINT,
  RAW_CROSSWORD_LAYOUT_CANONICAL,
  RESTORED_CANONICAL,
  RESTORED_FINGERPRINT,
} from './wp5f-normalized-vectors';

const REPO_ROOT = process.cwd();
const CORE_REL = 'src/lib/artwork/verification/normalizedMeaningCore.ts';
const FACADE_REL = 'src/lib/artwork/verification/normalizedMeaning.ts';
const ADAPTER_REL = 'src/lib/artwork/verification/normalizedMeaningResponse.ts';
const LEAF_REL = 'src/lib/artwork/virtualCanvasLayout.ts';
const STORE_REL = 'src/stores/artworkEditorStore.ts';
const SERIALIZER_REL = 'src/lib/artwork/artworkSerialization.ts';

const CROSSWORD_SEED = 424242;
const CROSSWORD_WORDS = ['MAKEIT', 'CROSSWORD', 'HELLO'];

// ── Fixtures (identical to the pre-split capturing implementation) ───────────

function canvasLayout(): ArtworkLayoutItem {
  return {
    id: CANVAS_LAYOUT_ID,
    name: 'Canvas',
    xCoordinate: 0,
    yCoordinate: 0,
    width: 0,
    height: 0,
    zCoordinate: 0,
    background: { ...DEFAULT_LAYOUT_BACKGROUND },
    hidden: false,
    locked: false,
    isCanvas: true,
  };
}

function textLayer(overrides: Partial<ArtworkPersistedLayer> = {}): ArtworkPersistedLayer {
  return {
    ...createDefaultArtworkTextLayer({ id: 'text-1', x: 10, y: 20, zCoordinate: 1 }),
    ...overrides,
  } as ArtworkPersistedLayer;
}

function placeholderImageLayer(): ArtworkPersistedLayer {
  return {
    ...createDefaultArtworkImageLayer({
      x: 30,
      y: 40,
      zCoordinate: 2,
      src: 'data:image/png;base64,PLACEHOLDER',
    }),
    name: 'Image',
    config: { placeholder: true, name: 'Placeholder', allowUpload: true },
  } as unknown as ArtworkPersistedLayer;
}

function crosswordLayer(): ArtworkPersistedLayer {
  const layer = createDefaultArtworkCrosswordLayer({ x: 50, y: 60, zCoordinate: 3 });
  return {
    ...layer,
    crossword: {
      ...layer.crossword,
      words: [...CROSSWORD_WORDS],
      generationSeed: CROSSWORD_SEED,
      layout: generateCrosswordLayout(CROSSWORD_WORDS, CROSSWORD_SEED),
    },
  } as unknown as ArtworkPersistedLayer;
}

function objectLayerWithChild(): ArtworkPersistedLayer {
  return {
    id: 'object-1',
    type: 'OBJECT',
    mode: 'object',
    objectRole: 'group',
    name: 'Group',
    xCoordinate: 70,
    yCoordinate: 80,
    width: 50,
    height: 60,
    naturalWidth: 50,
    naturalHeight: 60,
    zCoordinate: 4,
    rotation: 0,
    opacity: 100,
    transform: { flipX: false, flipY: false },
    layers: [textLayer({ id: 'nested-text-1', zCoordinate: 1 })],
  } as unknown as ArtworkPersistedLayer;
}

function baseSnapshot(): ArtworkEditorSnapshot {
  return {
    layoutItems: [
      canvasLayout(),
      {
        id: 'layout-a',
        name: 'Layout Alpha',
        xCoordinate: 100,
        yCoordinate: 120,
        width: 500,
        height: 500,
        zCoordinate: 1,
        background: { ...DEFAULT_LAYOUT_BACKGROUND },
        hidden: false,
        locked: false,
        layers: [textLayer(), placeholderImageLayer(), crosswordLayer(), objectLayerWithChild()],
      },
      {
        id: 'layout-b',
        name: 'Layout Beta',
        xCoordinate: 700,
        yCoordinate: 120,
        width: 500,
        height: 500,
        zCoordinate: 2,
        background: { ...DEFAULT_LAYOUT_BACKGROUND },
        hidden: false,
        locked: false,
        layers: [textLayer({ id: 'text-2', xCoordinate: 200, yCoordinate: 210 })],
      },
    ],
    activeLayoutId: 'layout-a',
    selectedLayoutIds: [],
  };
}

function equalZSnapshot(idA: string, idB: string): ArtworkEditorSnapshot {
  return {
    layoutItems: [
      canvasLayout(),
      {
        ...(baseSnapshot().layoutItems[1] as ArtworkLayoutItem),
        layers: [
          textLayer({ id: idA, zCoordinate: 5, name: 'Zulu' }),
          textLayer({ id: idB, zCoordinate: 5, name: 'Alpha' }),
        ],
      },
      baseSnapshot().layoutItems[2] as ArtworkLayoutItem,
    ],
    activeLayoutId: 'layout-a',
    selectedLayoutIds: [],
  };
}

function negZeroSnapshot(): ArtworkEditorSnapshot {
  const snapshot = baseSnapshot();
  const layout = snapshot.layoutItems[1] as ArtworkLayoutItem;
  (
    (layout.layers as unknown as Record<string, unknown>[])[0] as Record<string, unknown>
  ).xCoordinate = -1 * 0;
  return snapshot;
}

/** Deterministic frontend-only route fulfillment (ADR 0019 R8): ids + metadata only. */
function toGeneratedResponse(payload: CreateArtworkDto): ArtworkResponseDto {
  let layoutId = 1000;
  let layerId = 5000;
  const createdAt = '2026-09-18T00:00:00.000Z';
  return {
    id: 77,
    shopId: 3,
    type: 'ARTWORK',
    name: payload.name,
    renderOrder: 0,
    visible: true,
    locked: false,
    createdAt,
    updatedAt: createdAt,
    layouts: (payload.layouts ?? []).map((layout) => {
      const id = layoutId++;
      return {
        id,
        name: layout.name,
        artworkId: 77,
        createdAt,
        updatedAt: createdAt,
        layers: (layout.layers ?? []).map((layer) => ({
          ...layer,
          id: layerId++,
          ownerType: 'LAYOUT' as const,
          ownerId: id,
          hidden: false,
          locked: false,
          createdAt,
          updatedAt: createdAt,
        })),
      };
    }),
  } as ArtworkResponseDto;
}

describe('[ADR 0021 N3] closed compatibility surface and binding identity', () => {
  it('re-exports exactly the closed runtime export set', async () => {
    const facade = await import('@/lib/artwork/verification/normalizedMeaning');
    expect(Object.keys(facade).sort()).toEqual(
      [
        'NORMALIZED_MEANING_PROFILE_ID',
        'NORMALIZED_MEANING_SCHEMA_VERSION',
        'NORMALIZED_MEANING_UNUSABLE_CODE',
        'NormalizedMeaningUnusableError',
        'canonicalizeNormalizedMeaning',
        'extractRawCrosswordSemanticPayload',
        'fingerprintNormalizedMeaning',
        'normalizeArtworkProductMeaning',
        'normalizeArtworkResponseMeaning',
      ].sort(),
    );
  });

  it('preserves synchronous binding identity for every runtime export', async () => {
    const facade = await import('@/lib/artwork/verification/normalizedMeaning');
    const core = await import('@/lib/artwork/verification/normalizedMeaningCore');
    const response = await import('@/lib/artwork/verification/normalizedMeaningResponse');

    expect(facade.normalizeArtworkProductMeaning).toBe(core.normalizeArtworkProductMeaning);
    expect(facade.canonicalizeNormalizedMeaning).toBe(core.canonicalizeNormalizedMeaning);
    expect(facade.fingerprintNormalizedMeaning).toBe(core.fingerprintNormalizedMeaning);
    expect(facade.extractRawCrosswordSemanticPayload).toBe(core.extractRawCrosswordSemanticPayload);
    expect(facade.NormalizedMeaningUnusableError).toBe(core.NormalizedMeaningUnusableError);
    expect(facade.NORMALIZED_MEANING_SCHEMA_VERSION).toBe(core.NORMALIZED_MEANING_SCHEMA_VERSION);
    expect(facade.NORMALIZED_MEANING_PROFILE_ID).toBe(core.NORMALIZED_MEANING_PROFILE_ID);
    expect(facade.NORMALIZED_MEANING_UNUSABLE_CODE).toBe(core.NORMALIZED_MEANING_UNUSABLE_CODE);
    expect(facade.normalizeArtworkResponseMeaning).toBe(response.normalizeArtworkResponseMeaning);
  });

  it('facade contains no implementation, wrapper, lazy import, branch, or copied constant', () => {
    const source = readFileSync(path.join(REPO_ROOT, FACADE_REL), 'utf8');
    expect(source).toContain("export * from './normalizedMeaningCore';");
    expect(source).toContain(
      "export { normalizeArtworkResponseMeaning } from './normalizedMeaningResponse';",
    );
    expect(/function\s|=>\s*\{|require\(|import\(/.test(source)).toBe(false);
    expect(source.includes("'__canvas__'")).toBe(false);
    expect(source.includes('artwork-product-meaning-v1')).toBe(false);
  });
});

describe('[ADR 0021 N2] response-adapter refusal identity', () => {
  it('throws the same core-owned error class with exact name, code, and message', () => {
    const cases: Array<{ label: string; input: unknown; message: string }> = [
      {
        label: 'non-object',
        input: null,
        message: 'Artwork response DTO is not an object.',
      },
      {
        label: 'outer-envelope',
        input: { data: { layouts: [] }, message: 'ok', timestamp: 'now' },
        message:
          'normalizeArtworkResponseMeaning received the outer response envelope, not ArtworkResponseDto.',
      },
      {
        label: 'missing-layouts',
        input: { id: 1 },
        message: 'Artwork response DTO exposes no layouts array.',
      },
    ];
    for (const entry of cases) {
      let thrown: unknown;
      // Synchronous throwing: a plain try/catch observes it (no promise/thenable).
      try {
        const returned = normalizeArtworkResponseMeaning(entry.input as never);
        expect(returned, `${entry.label} must throw synchronously`).toBeUndefined();
      } catch (error) {
        thrown = error;
      }
      expect(thrown, `${entry.label} must throw`).toBeInstanceOf(NormalizedMeaningUnusableError);
      const error = thrown as NormalizedMeaningUnusableError;
      expect(error.name).toBe('NormalizedMeaningUnusableError');
      expect(error.code).toBe('NORMALIZED_MEANING_UNUSABLE');
      expect(error.message).toBe(entry.message);
    }
  });
});

describe('[ADR 0021 N3] named type-use fixtures for every exported interface', () => {
  it('allows named type use of the closed interfaces through core and facade', () => {
    const meaning: NormalizedArtworkMeaningV1 = normalizeArtworkProductMeaning(baseSnapshot());
    const layout: NormalizedLayoutMeaningV1 = meaning.layouts[0] as NormalizedLayoutMeaningV1;
    const layer: NormalizedLayerMeaningV1 = layout.layers[0] as NormalizedLayerMeaningV1;
    const raw: RawCrosswordSemanticPayloadV1 = {
      marker: true,
      generationSeed: 0,
      words: [],
      layout: {},
    };
    const viaFacade: import('@/lib/artwork/verification/normalizedMeaning').NormalizedArtworkMeaningV1 =
      meaning;
    expect(meaning.schemaVersion).toBe(1);
    expect(layout.layers.length).toBeGreaterThan(0);
    expect(layer).toBeDefined();
    expect(raw.marker).toBe(true);
    expect(viaFacade.profileId).toBe('artwork-product-meaning-v1');
  });
});

describe('[ADR 0021 N4] frozen pre-split regression vectors', () => {
  it('direct-core mixed snapshot matches the exact pre-split canonical string and fingerprint', () => {
    const normalized = normalizeArtworkProductMeaning(baseSnapshot());
    expect(canonicalizeNormalizedMeaning(normalized)).toBe(MIXED_CANONICAL);
    expect(fingerprintNormalizedMeaning(normalized)).toBe(MIXED_FINGERPRINT);
  });

  it('response adapter matches the exact pre-split restored result (structure and fingerprint)', () => {
    const payload = snapshotToCreateDto(baseSnapshot(), 'Roundtrip Artwork');
    const restored = normalizeArtworkResponseMeaning(toGeneratedResponse(payload));
    expect(canonicalizeNormalizedMeaning(restored)).toBe(RESTORED_CANONICAL);
    expect(fingerprintNormalizedMeaning(restored)).toBe(RESTORED_FINGERPRINT);
    // Structural equality in addition to fingerprint equality.
    expect(JSON.parse(canonicalizeNormalizedMeaning(restored))).toEqual(
      JSON.parse(RESTORED_CANONICAL),
    );
  });

  it('equal-z snapshot with volatile ids and source order changed is byte-identical', () => {
    const first = normalizeArtworkProductMeaning(equalZSnapshot('text-b', 'text-a'));
    const second = normalizeArtworkProductMeaning(equalZSnapshot('text-a', 'text-b'));
    expect(canonicalizeNormalizedMeaning(first)).toBe(EQUAL_Z_CANONICAL);
    expect(canonicalizeNormalizedMeaning(second)).toBe(EQUAL_Z_CANONICAL);
    expect(fingerprintNormalizedMeaning(first)).toBe(EQUAL_Z_FINGERPRINT);
    expect(JSON.parse(canonicalizeNormalizedMeaning(first))).toEqual(JSON.parse(EQUAL_Z_CANONICAL));
  });

  it('normalizes -0 to 0 with the exact pre-split bytes', () => {
    const normalized = normalizeArtworkProductMeaning(negZeroSnapshot());
    expect(canonicalizeNormalizedMeaning(normalized)).toBe(NEG_ZERO_CANONICAL);
    expect(fingerprintNormalizedMeaning(normalized)).toBe(NEG_ZERO_FINGERPRINT);
  });

  it('bounded raw Crossword layout canonicalization matches the pre-split vector', () => {
    const payload = snapshotToCreateDto(baseSnapshot(), 'Raw Artwork');
    const extracted = extractRawCrosswordSemanticPayload(payload);
    expect(extracted).not.toBeNull();
    expect(canonicalizeNormalizedMeaning(extracted?.layout)).toBe(RAW_CROSSWORD_LAYOUT_CANONICAL);
    expect(fingerprintNormalizedMeaning(extracted)).toBe(RAW_CROSSWORD_FINGERPRINT);
  });

  it('facade and direct-core calls produce identical vectors (no second normalizer)', async () => {
    const facade = await import('@/lib/artwork/verification/normalizedMeaning');
    const core = normalizeArtworkProductMeaning(baseSnapshot());
    const viaFacade = facade.normalizeArtworkProductMeaning(baseSnapshot());
    expect(canonicalizeNormalizedMeaning(viaFacade)).toBe(canonicalizeNormalizedMeaning(core));
    expect(facade.fingerprintNormalizedMeaning(viaFacade)).toBe(MIXED_FINGERPRINT);
  });
});

describe('[ADR 0021 N8] single virtual-canvas constant definition and compatibility', () => {
  it('store re-exports the exact leaf binding', () => {
    expect(storeId).toBe(leafId);
    expect(leafId).toBe('__canvas__');
  });

  it('has exactly one product definition of the constant, in the import-free leaf', () => {
    const definitions: string[] = [];
    const walk = (dir: string): void => {
      for (const entry of readdirSync(dir)) {
        const full = path.join(dir, entry);
        const stat = statSync(full);
        if (stat.isDirectory()) {
          if (entry === '__tests__' || entry === 'node_modules') continue;
          walk(full);
          continue;
        }
        if (!full.endsWith('.ts') && !full.endsWith('.tsx')) continue;
        const source = readFileSync(full, 'utf8');
        const matches = source.match(/export const CANVAS_LAYOUT_ID = '__canvas__' as const;/g);
        if (matches) for (let i = 0; i < matches.length; i += 1) definitions.push(full);
      }
    };
    walk(path.join(REPO_ROOT, 'src'));
    expect(definitions).toHaveLength(1);
    expect(path.relative(REPO_ROOT, definitions[0] as string)).toBe(LEAF_REL);
  });

  it('store and serializer reach the leaf directly, not a duplicated literal', () => {
    const store = readFileSync(path.join(REPO_ROOT, STORE_REL), 'utf8');
    expect(store).toContain(
      "import { CANVAS_LAYOUT_ID } from '@/lib/artwork/virtualCanvasLayout';",
    );
    expect(store).toContain('export { CANVAS_LAYOUT_ID };');
    expect(store.includes("export const CANVAS_LAYOUT_ID = '__canvas__'")).toBe(false);

    const serializer = readFileSync(path.join(REPO_ROOT, SERIALIZER_REL), 'utf8');
    expect(serializer).toContain(
      "import { CANVAS_LAYOUT_ID } from '@/lib/artwork/virtualCanvasLayout';",
    );
    const storeImport =
      serializer
        .match(/import\s+\{[^}]*\}\s+from\s+'@\/stores\/artworkEditorStore';/g)
        ?.join('\n') ?? '';
    expect(storeImport.includes('CANVAS_LAYOUT_ID')).toBe(false);
  });

  it('leaf imports nothing', () => {
    const leaf = readFileSync(path.join(REPO_ROOT, LEAF_REL), 'utf8');
    expect(/^import\s/m.test(leaf)).toBe(false);
  });
});

describe('[ADR 0021 N5] deterministic import-graph classification and cycle audit', () => {
  interface Edge {
    from: string;
    to: string;
    kind: 'type-declaration' | 'type-specifier' | 'value' | 're-export';
  }

  const SCOPED: Record<string, string> = {
    [LEAF_REL]: 'leaf',
    [CORE_REL]: 'core',
    [ADAPTER_REL]: 'adapter',
    [FACADE_REL]: 'facade',
    [STORE_REL]: 'store',
    [SERIALIZER_REL]: 'serializer',
    '@/lib/artwork/virtualCanvasLayout': 'leaf',
    './normalizedMeaningCore': 'core',
    './normalizedMeaningResponse': 'adapter',
    '@/stores/artworkEditorStore': 'store',
    '@/lib/artwork/artworkSerialization': 'serializer',
    './normalizedMeaning': 'facade',
  };

  function resolveModule(specifier: string, fileRel: string): string | null {
    if (SCOPED[specifier]) return SCOPED[specifier];
    if (specifier.startsWith('.')) {
      const resolved = path.posix.normalize(
        path.posix.join(path.posix.dirname(fileRel), specifier),
      );
      return SCOPED[`${resolved}.ts`] ?? null;
    }
    return null;
  }

  function auditEdges(fileRel: string): Edge[] {
    const from = SCOPED[fileRel] as string;
    const source = readFileSync(path.join(REPO_ROOT, fileRel), 'utf8');
    const edges: Edge[] = [];
    const importedValues = new Map<string, string>();

    // Re-exports with an explicit module: `export * from` / `export { ... } from`.
    for (const match of source.matchAll(
      /^export\s+(?:type\s+)?(?:\*|\{[^}]*\})\s+from\s+'([^']+)';/gm,
    )) {
      const target = resolveModule(match[1] as string, fileRel);
      if (target) edges.push({ from, to: target, kind: 're-export' });
    }

    // Imports (including multi-line), classified per declaration and specifier.
    for (const match of source.matchAll(/^import\s+(type\s+)?([^;]*?)\s+from\s+'([^']+)';/gm)) {
      const declarationType = match[1] !== undefined;
      const clause = (match[2] as string).replace(/^\s*/, '');
      const target = resolveModule(match[3] as string, fileRel);
      if (!target) continue;
      if (declarationType) {
        edges.push({ from, to: target, kind: 'type-declaration' });
        continue;
      }
      const named = clause.match(/\{([^}]*)\}/);
      const specifiers =
        named?.[1]
          .split(',')
          .map((entry) => entry.trim())
          .filter((entry) => entry.length > 0) ?? [];
      const hasValueSpecifier = specifiers.some((entry) => !entry.startsWith('type '));
      const hasTypeSpecifier = specifiers.some((entry) => entry.startsWith('type '));
      const isBareImport = named === null;
      for (const specifier of specifiers) {
        if (specifier.startsWith('type ')) continue;
        const [importedName] = specifier.split(/\s+as\s+/);
        if (importedName) importedValues.set(importedName, target);
      }
      if (hasValueSpecifier || isBareImport) edges.push({ from, to: target, kind: 'value' });
      if (hasTypeSpecifier) edges.push({ from, to: target, kind: 'type-specifier' });
    }

    // Local re-exports of an imported binding: `export { X };`.
    for (const match of source.matchAll(/^export\s+\{([^}]*)\};/gm)) {
      for (const entry of (match[1] as string).split(',')) {
        const [localName] = entry.trim().split(/\s+as\s+/);
        if (!localName) continue;
        const target = importedValues.get(localName);
        if (target) edges.push({ from, to: target, kind: 're-export' });
      }
    }
    return edges;
  }

  const allEdges: Edge[] = Object.keys(SCOPED)
    .filter((key) => key.endsWith('.ts'))
    .flatMap(auditEdges);

  it('classifies the core, adapter, facade, leaf, store, and serializer edges exactly', () => {
    expect(allEdges.filter((edge) => edge.from === 'leaf')).toEqual([]);

    expect(allEdges.filter((edge) => edge.from === 'core')).toEqual([
      { from: 'core', to: 'leaf', kind: 'value' },
      { from: 'core', to: 'store', kind: 'type-declaration' },
    ]);

    expect(allEdges.filter((edge) => edge.from === 'adapter')).toEqual([
      { from: 'adapter', to: 'serializer', kind: 'value' },
      { from: 'adapter', to: 'core', kind: 'value' },
      { from: 'adapter', to: 'core', kind: 'type-specifier' },
    ]);

    expect(allEdges.filter((edge) => edge.from === 'facade')).toEqual([
      { from: 'facade', to: 'core', kind: 're-export' },
      { from: 'facade', to: 'adapter', kind: 're-export' },
    ]);

    const storeEdges = allEdges.filter((edge) => edge.from === 'store');
    expect(storeEdges).toContainEqual({ from: 'store', to: 'leaf', kind: 'value' });
    expect(storeEdges).toContainEqual({ from: 'store', to: 'leaf', kind: 're-export' });
  });

  it('proves the core store dependency is type-only and absent from the runtime graph', () => {
    const coreEdges = allEdges.filter((edge) => edge.from === 'core');
    const coreRuntimeTargets = coreEdges
      .filter((edge) => edge.kind === 'value' || edge.kind === 're-export')
      .map((edge) => edge.to);
    expect(coreRuntimeTargets).toEqual(['leaf']);
    expect(coreRuntimeTargets).not.toContain('store');
  });

  it('proves the scoped runtime graph (type edges excluded) is acyclic', () => {
    const adjacency = new Map<string, string[]>();
    for (const edge of allEdges) {
      if (edge.kind === 'type-declaration' || edge.kind === 'type-specifier') continue;
      adjacency.set(edge.from, [...(adjacency.get(edge.from) ?? []), edge.to]);
    }
    const visiting = new Set<string>();
    const visited = new Set<string>();
    const visit = (node: string, stack: string[]): void => {
      if (visiting.has(node)) throw new Error(`cycle: ${[...stack, node].join(' -> ')}`);
      if (visited.has(node)) return;
      visiting.add(node);
      for (const next of adjacency.get(node) ?? []) visit(next, [...stack, node]);
      visiting.delete(node);
      visited.add(node);
    };
    for (const node of adjacency.keys()) expect(() => visit(node, [])).not.toThrow();
  });

  it('proves only one normalized projection implementation exists (core) among the scoped modules', () => {
    const core = readFileSync(path.join(REPO_ROOT, CORE_REL), 'utf8');
    const adapter = readFileSync(path.join(REPO_ROOT, ADAPTER_REL), 'utf8');
    const facade = readFileSync(path.join(REPO_ROOT, FACADE_REL), 'utf8');
    expect(core).toContain('export function normalizeArtworkProductMeaning');
    expect(adapter.includes('function normalizeArtworkProductMeaning')).toBe(false);
    expect(facade.includes('function normalizeArtworkProductMeaning')).toBe(false);
  });
});

describe('[ADR 0021 N6] raw Node/tsx child-process core import proof', () => {
  it('imports the exact core .ts path from the repository root and exercises meaning', () => {
    const script = `import('./${CORE_REL}').then((core) => {
      const interop = new Set(['default', 'module.exports']);
      const names = Object.keys(core).filter((name) => !interop.has(name)).sort();
      const snapshot = {
        layoutItems: [
          { id: '__canvas__', isCanvas: true, layers: [] },
          {
            id: 'l1', name: 'L', xCoordinate: 0, yCoordinate: 0, width: 1, height: 1,
            zCoordinate: 1, hidden: false, locked: false,
            layers: [
              { id: 'x', type: 'TEXT', name: 'T', zCoordinate: 0, xCoordinate: 1,
                yCoordinate: 2, width: 3, height: 4, opacity: 1, rotation: 0,
                hidden: false, locked: false, content: { text: 'hi' } }
            ]
          }
        ]
      };
      const normalized = core.normalizeArtworkProductMeaning(snapshot);
      process.stdout.write(JSON.stringify({
        names,
        hasResponseNormalizer: 'normalizeArtworkResponseMeaning' in core,
        schemaVersion: normalized.schemaVersion,
        profileId: normalized.profileId,
        canonical: core.canonicalizeNormalizedMeaning(normalized),
        fingerprint: core.fingerprintNormalizedMeaning(normalized),
      }));
    }).catch((error) => {
      process.stderr.write(String(error && error.stack ? error.stack : error));
      process.exit(1);
    });`;

    const stdout = execFileSync(
      process.execPath,
      [path.join(REPO_ROOT, 'node_modules/tsx/dist/cli.mjs'), '-e', script],
      { cwd: REPO_ROOT, encoding: 'utf8' },
    );
    const result = JSON.parse(stdout) as {
      names: string[];
      hasResponseNormalizer: boolean;
      schemaVersion: number;
      profileId: string;
      canonical: string;
      fingerprint: string;
    };
    expect(result.names).toEqual(
      [
        'NORMALIZED_MEANING_PROFILE_ID',
        'NORMALIZED_MEANING_SCHEMA_VERSION',
        'NORMALIZED_MEANING_UNUSABLE_CODE',
        'NormalizedMeaningUnusableError',
        'canonicalizeNormalizedMeaning',
        'extractRawCrosswordSemanticPayload',
        'fingerprintNormalizedMeaning',
        'normalizeArtworkProductMeaning',
      ].sort(),
    );
    expect(result.hasResponseNormalizer).toBe(false);
    expect(result.schemaVersion).toBe(1);
    expect(result.profileId).toBe('artwork-product-meaning-v1');
    expect(typeof result.canonical).toBe('string');
    expect(result.fingerprint).toMatch(/^[0-9a-f]{16}$/);
  }, 120_000);
});

describe('[ADR 0021 N7] toolkit consumer import enforcement', () => {
  const SKILL_ROOT = path.join(REPO_ROOT, '.pi/skills/verify-artwork-editor');

  function collectFiles(dir: string, predicate: (rel: string) => boolean): string[] {
    const found: string[] = [];
    const walk = (current: string): void => {
      for (const entry of readdirSync(current)) {
        const full = path.join(current, entry);
        if (statSync(full).isDirectory()) {
          walk(full);
          continue;
        }
        const rel = path.relative(SKILL_ROOT, full);
        if (predicate(rel)) found.push(full);
      }
    };
    walk(dir);
    return found;
  }

  function importedModules(source: string): string[] {
    return [
      ...source.matchAll(/^import\s+(?:type\s+)?[^;]*?from\s+'([^']+)';/gm),
      ...source.matchAll(/^export\s+(?:type\s+)?(?:\*|\{[^}]*\})\s+from\s+'([^']+)';/gm),
    ].map((match) => match[1] as string);
  }

  it('prohibits toolkit production source from importing the facade, adapter, or serializer', () => {
    const files = collectFiles(
      path.join(SKILL_ROOT, 'src'),
      (rel) => rel.endsWith('.ts') || rel.endsWith('.tsx'),
    );
    for (const file of files) {
      const source = readFileSync(file, 'utf8');
      for (const module of importedModules(source)) {
        if (module.includes('artworkSerialization')) {
          throw new Error(
            `${path.relative(SKILL_ROOT, file)} must not import artworkSerialization`,
          );
        }
        if (module.includes('normalizedMeaningResponse')) {
          throw new Error(
            `${path.relative(SKILL_ROOT, file)} must not import the response adapter`,
          );
        }
        if (/(^|\/)normalizedMeaning$/.test(module)) {
          throw new Error(`${path.relative(SKILL_ROOT, file)} must not import the facade`);
        }
        if (module.includes('verification/normalizedMeaning')) {
          expect(module).toContain('normalizedMeaningCore');
        }
      }
    }
  });

  it('requires snapshot-only browser tests to use the core directly', () => {
    const files = collectFiles(path.join(SKILL_ROOT, 'tests/browser'), (rel) =>
      rel.endsWith('.ts'),
    );
    for (const file of files) {
      const source = readFileSync(file, 'utf8');
      for (const module of importedModules(source)) {
        expect(module.includes('normalizedMeaningResponse')).toBe(false);
        expect(/(^|\/)normalizedMeaning$/.test(module)).toBe(false);
      }
    }
    const guardedEscape = readFileSync(
      path.join(SKILL_ROOT, 'tests/browser/wp5f-guarded-escape.browser.test.ts'),
      'utf8',
    );
    expect(guardedEscape).toContain('verification/normalizedMeaningCore');
    expect(guardedEscape.includes("verification/normalizedMeaning'")).toBe(false);
  });
});
