import { canonicalize, sha256Hex } from '../canonical/canonicalize';
import type { GovernedPathEntry } from './provenance';

/** Authoritative post-activation P8-A2 closure, regenerated from active entry roots. */
export const PROVENANCE_COMPONENT_POLICY_VERSION = 2 as const;
export const PROVENANCE_COMPONENT_POLICY_PHASE = 'post-activation' as const;
export const PROVENANCE_COMPONENT_POLICY_AUTHORITATIVE = true as const;

export const PROVENANCE_ACTIVE_ENTRY_ROOTS = Object.freeze({
  diagnostic: Object.freeze(['src/cli/diagnostic.ts']),
  doctor: Object.freeze(['src/cli/doctor.ts']),
  'production-absence': Object.freeze([
    'src/cli/production-absence.ts',
  ]),
  'suite-child': Object.freeze([
    'src/cli/suite.ts',
    'src/cli/diagnostic.ts',
  ]),
} as const);

export type ProvenanceFlow = keyof typeof PROVENANCE_ACTIVE_ENTRY_ROOTS;
export type ProvenanceComponentName =
  | 'cliBootstrapDigest'
  | 'runnerDigest'
  | 'evidenceWriterDigest'
  | 'verifierDigest';

export interface ProvenanceComponentPolicy {
  readonly version: typeof PROVENANCE_COMPONENT_POLICY_VERSION;
  readonly phase: typeof PROVENANCE_COMPONENT_POLICY_PHASE;
  readonly authoritativeForFinalProvenance: true;
  readonly activeEntryRoots: typeof PROVENANCE_ACTIVE_ENTRY_ROOTS;
  readonly frozenClosures: Readonly<Record<ProvenanceFlow, readonly string[]>>;
}

export const PROVENANCE_COMPONENT_POLICY: ProvenanceComponentPolicy = Object.freeze({
  version: PROVENANCE_COMPONENT_POLICY_VERSION,
  phase: PROVENANCE_COMPONENT_POLICY_PHASE,
  authoritativeForFinalProvenance: true,
  activeEntryRoots: PROVENANCE_ACTIVE_ENTRY_ROOTS,
  frozenClosures: Object.freeze({
    diagnostic: Object.freeze([
      'src/adapters/crossword-live-facts.ts',
      'src/adapters/default-specialized.ts',
      'src/adapters/generated-specialized.ts',
      'src/adapters/history-live-facts.ts',
      'src/adapters/image-live-facts.ts',
      'src/adapters/image-specialized.ts',
      'src/adapters/object-live-facts.ts',
      'src/adapters/object-specialized.ts',
      'src/adapters/registry.ts',
      'src/adapters/restore-live-facts.ts',
      'src/adapters/text-live-facts.ts',
      'src/adapters/text-specialized.ts',
      'src/allocation/allocate.ts',
      'src/allocation/lease.ts',
      'src/allocation/ownership.ts',
      'src/allocation/port-reservation.ts',
      'src/allocation/process-identity.ts',
      'src/allocation/reserve.ts',
      'src/browser/doctor.ts',
      'src/browser/guarded-setup.ts',
      'src/browser/launch.ts',
      'src/browser/primitives.ts',
      'src/browser/public-controls.ts',
      'src/browser/seam.ts',
      'src/canonical/canonicalize.ts',
      'src/canonical/identity.ts',
      'src/canonical/package8-identity.ts',
      'src/catalogue/correctness-compatibility.ts',
      'src/catalogue/correctness.ts',
      'src/catalogue/fingerprint.ts',
      'src/catalogue/fixtures.ts',
      'src/catalogue/load.ts',
      'src/catalogue/resolve.ts',
      'src/catalogue/resources.ts',
      'src/catalogue/wp5-compatibility-oracle.ts',
      'src/cleanup/cleanup.ts',
      'src/cli/diagnostic.ts',
      'src/cli/output.ts',
      'src/cli/termination-state.ts',
      'src/cli/termination.ts',
      'src/commands/command-context.ts',
      'src/commands/doctor-command-context.ts',
      'src/commands/production-absence-command-context.ts',
      'src/contracts/adapter.ts',
      'src/contracts/case-model.ts',
      'src/contracts/catalogues.ts',
      'src/contracts/command-check.ts',
      'src/contracts/correctness.ts',
      'src/contracts/coverage.ts',
      'src/contracts/crossword-observation.ts',
      'src/contracts/crossword.ts',
      'src/contracts/diagnostics.ts',
      'src/contracts/discriminants.ts',
      'src/contracts/evidence-transaction.ts',
      'src/contracts/execution.ts',
      'src/contracts/final-public-record.ts',
      'src/contracts/final-record-reader.ts',
      'src/contracts/final-record-v4.ts',
      'src/contracts/final-result-dto.ts',
      'src/contracts/final-suite-record.ts',
      'src/contracts/fixtures.ts',
      'src/contracts/geometry-v2.ts',
      'src/contracts/geometry-v3.ts',
      'src/contracts/history-observation.ts',
      'src/contracts/observation.ts',
      'src/contracts/planner-outputs.ts',
      'src/contracts/production-absence.ts',
      'src/contracts/raster.ts',
      'src/contracts/resources.ts',
      'src/contracts/restore-observation.ts',
      'src/contracts/result-agreement.ts',
      'src/contracts/runtime.ts',
      'src/contracts/schema-versions.ts',
      'src/contracts/seam.ts',
      'src/contracts/selection-clear.ts',
      'src/contracts/suite.ts',
      'src/contracts/wall-clock.ts',
      'src/contracts/workflows.ts',
      'src/coverage/account.ts',
      'src/coverage/load.ts',
      'src/coverage/resolve.ts',
      'src/coverage/select.ts',
      'src/coverage/validate.ts',
      'src/evidence/cleanup-authority.ts',
      'src/evidence/final-reader.ts',
      'src/evidence/final-suite-writer.ts',
      'src/evidence/final-writer.ts',
      'src/evidence/guard.ts',
      'src/evidence/private-snapshot.ts',
      'src/evidence/provenance-collector.ts',
      'src/evidence/provenance-component-policy.ts',
      'src/evidence/provenance.ts',
      'src/evidence/public-dto.ts',
      'src/evidence/publication.ts',
      'src/evidence/reference-graph.ts',
      'src/evidence/sanitize.ts',
      'src/evidence/semantic-digest.ts',
      'src/evidence/transaction.ts',
      'src/evidence/writer.ts',
      'src/kernels/crossword-kernel.ts',
      'src/kernels/history-kernel.ts',
      'src/kernels/image-kernel.ts',
      'src/kernels/nested-object-kernel.ts',
      'src/kernels/restore-kernel.ts',
      'src/kernels/text-kernel.ts',
      'src/oracles/crossword.ts',
      'src/oracles/evaluate.ts',
      'src/oracles/geometry.ts',
      'src/oracles/history.ts',
      'src/oracles/image.ts',
      'src/oracles/nested-object.ts',
      'src/oracles/profile-registry.ts',
      'src/oracles/restore.ts',
      'src/oracles/warped-text.ts',
      'src/orchestration/command-execution.ts',
      'src/orchestration/diagnostic-execution.ts',
      'src/orchestration/doctor-command-execution.ts',
      'src/orchestration/final-active-path.ts',
      'src/orchestration/production-absence-command-execution.ts',
      'src/orchestration/suite-execution.ts',
      'src/planner/compile-plan.ts',
      'src/planner/execution-materialization.ts',
      'src/planner/execution-support.ts',
      'src/planner/launchability.ts',
      'src/planner/materialize.ts',
      'src/planner/normalize-intent.ts',
      'src/planner/plan-case.ts',
      'src/planner/preflight.ts',
      'src/readiness/coherent-capture.ts',
      'src/readiness/correlated-gate.ts',
      'src/readiness/profile-registry.ts',
      'src/readiness/raster-currentness.ts',
      'src/registry/reconcile.ts',
      'src/registry/validate.ts',
      'src/resources/request-log.ts',
      'src/resources/resolve.ts',
      'src/resources/routes.ts',
      'src/routing/resolve.ts',
      'src/runtime/action-cycle.ts',
      'src/runtime/config-snapshot.ts',
      'src/runtime/environment-facts.ts',
      'src/runtime/environment.ts',
      'src/runtime/execute-crossword-plan.ts',
      'src/runtime/execute-history-plan.ts',
      'src/runtime/execute-image-plan.ts',
      'src/runtime/execute-plan.ts',
      'src/runtime/execute-restore-plan.ts',
      'src/runtime/launch.ts',
      'src/runtime/outcomes.ts',
      'src/runtime/paths.ts',
      'src/runtime/process-group.ts',
      'src/runtime/readiness.ts',
      'src/runtime/result-outcome.ts',
      'src/runtime/run-id.ts',
      'src/workflows/execute.ts',
      'src/workflows/steps.ts',
    ]),
    doctor: Object.freeze([
      'src/adapters/crossword-live-facts.ts',
      'src/adapters/default-specialized.ts',
      'src/adapters/doctor-command-live-facts.ts',
      'src/adapters/generated-specialized.ts',
      'src/adapters/history-live-facts.ts',
      'src/adapters/image-live-facts.ts',
      'src/adapters/image-specialized.ts',
      'src/adapters/object-live-facts.ts',
      'src/adapters/object-specialized.ts',
      'src/adapters/registry.ts',
      'src/adapters/restore-live-facts.ts',
      'src/adapters/text-live-facts.ts',
      'src/adapters/text-specialized.ts',
      'src/allocation/allocate.ts',
      'src/allocation/lease.ts',
      'src/allocation/ownership.ts',
      'src/allocation/port-reservation.ts',
      'src/allocation/process-identity.ts',
      'src/allocation/reserve.ts',
      'src/browser/doctor.ts',
      'src/browser/guarded-setup.ts',
      'src/browser/launch.ts',
      'src/browser/primitives.ts',
      'src/browser/public-controls.ts',
      'src/browser/seam.ts',
      'src/canonical/canonicalize.ts',
      'src/canonical/identity.ts',
      'src/canonical/package8-identity.ts',
      'src/catalogue/correctness-compatibility.ts',
      'src/catalogue/correctness.ts',
      'src/catalogue/fingerprint.ts',
      'src/catalogue/fixtures.ts',
      'src/catalogue/load.ts',
      'src/catalogue/resolve.ts',
      'src/catalogue/resources.ts',
      'src/catalogue/wp5-compatibility-oracle.ts',
      'src/cleanup/cleanup.ts',
      'src/cli/doctor.ts',
      'src/cli/output.ts',
      'src/cli/termination-state.ts',
      'src/cli/termination.ts',
      'src/commands/command-context.ts',
      'src/commands/doctor-command-context.ts',
      'src/commands/production-absence-command-context.ts',
      'src/contracts/adapter.ts',
      'src/contracts/case-model.ts',
      'src/contracts/catalogues.ts',
      'src/contracts/command-check.ts',
      'src/contracts/correctness.ts',
      'src/contracts/coverage.ts',
      'src/contracts/crossword-observation.ts',
      'src/contracts/crossword.ts',
      'src/contracts/diagnostics.ts',
      'src/contracts/discriminants.ts',
      'src/contracts/evidence-transaction.ts',
      'src/contracts/execution.ts',
      'src/contracts/final-public-record.ts',
      'src/contracts/final-record-reader.ts',
      'src/contracts/final-record-v4.ts',
      'src/contracts/final-result-dto.ts',
      'src/contracts/final-suite-record.ts',
      'src/contracts/fixtures.ts',
      'src/contracts/geometry-v2.ts',
      'src/contracts/geometry-v3.ts',
      'src/contracts/history-observation.ts',
      'src/contracts/observation.ts',
      'src/contracts/planner-outputs.ts',
      'src/contracts/production-absence.ts',
      'src/contracts/raster.ts',
      'src/contracts/resources.ts',
      'src/contracts/restore-observation.ts',
      'src/contracts/result-agreement.ts',
      'src/contracts/runtime.ts',
      'src/contracts/schema-versions.ts',
      'src/contracts/seam.ts',
      'src/contracts/selection-clear.ts',
      'src/contracts/suite.ts',
      'src/contracts/wall-clock.ts',
      'src/contracts/workflows.ts',
      'src/coverage/account.ts',
      'src/coverage/load.ts',
      'src/coverage/resolve.ts',
      'src/coverage/select.ts',
      'src/coverage/validate.ts',
      'src/evidence/cleanup-authority.ts',
      'src/evidence/final-reader.ts',
      'src/evidence/final-suite-writer.ts',
      'src/evidence/final-writer.ts',
      'src/evidence/guard.ts',
      'src/evidence/private-snapshot.ts',
      'src/evidence/provenance-collector.ts',
      'src/evidence/provenance-component-policy.ts',
      'src/evidence/provenance.ts',
      'src/evidence/public-dto.ts',
      'src/evidence/publication.ts',
      'src/evidence/reference-graph.ts',
      'src/evidence/sanitize.ts',
      'src/evidence/semantic-digest.ts',
      'src/evidence/transaction.ts',
      'src/evidence/writer.ts',
      'src/kernels/crossword-kernel.ts',
      'src/kernels/history-kernel.ts',
      'src/kernels/image-kernel.ts',
      'src/kernels/nested-object-kernel.ts',
      'src/kernels/restore-kernel.ts',
      'src/kernels/text-kernel.ts',
      'src/oracles/crossword.ts',
      'src/oracles/evaluate.ts',
      'src/oracles/geometry.ts',
      'src/oracles/history.ts',
      'src/oracles/image.ts',
      'src/oracles/nested-object.ts',
      'src/oracles/profile-registry.ts',
      'src/oracles/restore.ts',
      'src/oracles/warped-text.ts',
      'src/orchestration/command-execution.ts',
      'src/orchestration/diagnostic-execution.ts',
      'src/orchestration/doctor-command-execution.ts',
      'src/orchestration/final-active-path.ts',
      'src/orchestration/production-absence-command-execution.ts',
      'src/orchestration/suite-execution.ts',
      'src/planner/compile-plan.ts',
      'src/planner/execution-materialization.ts',
      'src/planner/launchability.ts',
      'src/planner/materialize.ts',
      'src/planner/normalize-intent.ts',
      'src/planner/plan-case.ts',
      'src/planner/preflight.ts',
      'src/readiness/coherent-capture.ts',
      'src/readiness/correlated-gate.ts',
      'src/readiness/profile-registry.ts',
      'src/readiness/raster-currentness.ts',
      'src/registry/reconcile.ts',
      'src/registry/validate.ts',
      'src/resources/request-log.ts',
      'src/resources/resolve.ts',
      'src/resources/routes.ts',
      'src/routing/resolve.ts',
      'src/runtime/action-cycle.ts',
      'src/runtime/config-snapshot.ts',
      'src/runtime/environment-facts.ts',
      'src/runtime/environment.ts',
      'src/runtime/execute-crossword-plan.ts',
      'src/runtime/execute-history-plan.ts',
      'src/runtime/execute-image-plan.ts',
      'src/runtime/execute-plan.ts',
      'src/runtime/execute-restore-plan.ts',
      'src/runtime/launch.ts',
      'src/runtime/outcomes.ts',
      'src/runtime/paths.ts',
      'src/runtime/process-group.ts',
      'src/runtime/readiness.ts',
      'src/runtime/result-outcome.ts',
      'src/runtime/run-id.ts',
      'src/workflows/execute.ts',
      'src/workflows/steps.ts',
    ]),
    'production-absence': Object.freeze([
      'src/adapters/crossword-live-facts.ts',
      'src/adapters/default-specialized.ts',
      'src/adapters/generated-specialized.ts',
      'src/adapters/history-live-facts.ts',
      'src/adapters/image-live-facts.ts',
      'src/adapters/image-specialized.ts',
      'src/adapters/object-live-facts.ts',
      'src/adapters/object-specialized.ts',
      'src/adapters/production-absence-command-live-facts.ts',
      'src/adapters/registry.ts',
      'src/adapters/restore-live-facts.ts',
      'src/adapters/text-live-facts.ts',
      'src/adapters/text-specialized.ts',
      'src/allocation/allocate.ts',
      'src/allocation/lease.ts',
      'src/allocation/ownership.ts',
      'src/allocation/port-reservation.ts',
      'src/allocation/process-identity.ts',
      'src/allocation/reserve.ts',
      'src/browser/doctor.ts',
      'src/browser/guarded-setup.ts',
      'src/browser/launch.ts',
      'src/browser/primitives.ts',
      'src/browser/production-absence.ts',
      'src/browser/public-controls.ts',
      'src/browser/seam.ts',
      'src/canonical/canonicalize.ts',
      'src/canonical/identity.ts',
      'src/canonical/package8-identity.ts',
      'src/catalogue/correctness-compatibility.ts',
      'src/catalogue/correctness.ts',
      'src/catalogue/fingerprint.ts',
      'src/catalogue/fixtures.ts',
      'src/catalogue/load.ts',
      'src/catalogue/resolve.ts',
      'src/catalogue/resources.ts',
      'src/catalogue/wp5-compatibility-oracle.ts',
      'src/cleanup/cleanup.ts',
      'src/cli/output.ts',
      'src/cli/production-absence.ts',
      'src/cli/termination-state.ts',
      'src/cli/termination.ts',
      'src/commands/command-context.ts',
      'src/commands/doctor-command-context.ts',
      'src/commands/production-absence-command-context.ts',
      'src/contracts/adapter.ts',
      'src/contracts/case-model.ts',
      'src/contracts/catalogues.ts',
      'src/contracts/command-check.ts',
      'src/contracts/correctness.ts',
      'src/contracts/coverage.ts',
      'src/contracts/crossword-observation.ts',
      'src/contracts/crossword.ts',
      'src/contracts/diagnostics.ts',
      'src/contracts/discriminants.ts',
      'src/contracts/evidence-transaction.ts',
      'src/contracts/execution.ts',
      'src/contracts/final-public-record.ts',
      'src/contracts/final-record-reader.ts',
      'src/contracts/final-record-v4.ts',
      'src/contracts/final-result-dto.ts',
      'src/contracts/final-suite-record.ts',
      'src/contracts/fixtures.ts',
      'src/contracts/geometry-v2.ts',
      'src/contracts/geometry-v3.ts',
      'src/contracts/history-observation.ts',
      'src/contracts/observation.ts',
      'src/contracts/planner-outputs.ts',
      'src/contracts/production-absence.ts',
      'src/contracts/raster.ts',
      'src/contracts/resources.ts',
      'src/contracts/restore-observation.ts',
      'src/contracts/result-agreement.ts',
      'src/contracts/runtime.ts',
      'src/contracts/schema-versions.ts',
      'src/contracts/seam.ts',
      'src/contracts/selection-clear.ts',
      'src/contracts/suite.ts',
      'src/contracts/wall-clock.ts',
      'src/contracts/workflows.ts',
      'src/coverage/account.ts',
      'src/coverage/load.ts',
      'src/coverage/resolve.ts',
      'src/coverage/select.ts',
      'src/coverage/validate.ts',
      'src/evidence/cleanup-authority.ts',
      'src/evidence/final-reader.ts',
      'src/evidence/final-suite-writer.ts',
      'src/evidence/final-writer.ts',
      'src/evidence/guard.ts',
      'src/evidence/private-snapshot.ts',
      'src/evidence/provenance-collector.ts',
      'src/evidence/provenance-component-policy.ts',
      'src/evidence/provenance.ts',
      'src/evidence/public-dto.ts',
      'src/evidence/publication.ts',
      'src/evidence/reference-graph.ts',
      'src/evidence/sanitize.ts',
      'src/evidence/semantic-digest.ts',
      'src/evidence/transaction.ts',
      'src/evidence/writer.ts',
      'src/kernels/crossword-kernel.ts',
      'src/kernels/history-kernel.ts',
      'src/kernels/image-kernel.ts',
      'src/kernels/nested-object-kernel.ts',
      'src/kernels/restore-kernel.ts',
      'src/kernels/text-kernel.ts',
      'src/oracles/crossword.ts',
      'src/oracles/evaluate.ts',
      'src/oracles/geometry.ts',
      'src/oracles/history.ts',
      'src/oracles/image.ts',
      'src/oracles/nested-object.ts',
      'src/oracles/profile-registry.ts',
      'src/oracles/restore.ts',
      'src/oracles/warped-text.ts',
      'src/orchestration/command-execution.ts',
      'src/orchestration/diagnostic-execution.ts',
      'src/orchestration/doctor-command-execution.ts',
      'src/orchestration/final-active-path.ts',
      'src/orchestration/production-absence-command-execution.ts',
      'src/orchestration/suite-execution.ts',
      'src/planner/compile-plan.ts',
      'src/planner/execution-materialization.ts',
      'src/planner/launchability.ts',
      'src/planner/materialize.ts',
      'src/planner/normalize-intent.ts',
      'src/planner/plan-case.ts',
      'src/planner/preflight.ts',
      'src/readiness/coherent-capture.ts',
      'src/readiness/correlated-gate.ts',
      'src/readiness/profile-registry.ts',
      'src/readiness/raster-currentness.ts',
      'src/registry/reconcile.ts',
      'src/registry/validate.ts',
      'src/resources/request-log.ts',
      'src/resources/resolve.ts',
      'src/resources/routes.ts',
      'src/routing/resolve.ts',
      'src/runtime/action-cycle.ts',
      'src/runtime/config-snapshot.ts',
      'src/runtime/environment-facts.ts',
      'src/runtime/environment.ts',
      'src/runtime/execute-crossword-plan.ts',
      'src/runtime/execute-history-plan.ts',
      'src/runtime/execute-image-plan.ts',
      'src/runtime/execute-plan.ts',
      'src/runtime/execute-restore-plan.ts',
      'src/runtime/launch.ts',
      'src/runtime/outcomes.ts',
      'src/runtime/paths.ts',
      'src/runtime/process-group.ts',
      'src/runtime/production-server.ts',
      'src/runtime/readiness.ts',
      'src/runtime/result-outcome.ts',
      'src/runtime/run-id.ts',
      'src/runtime/static-scan.ts',
      'src/workflows/execute.ts',
      'src/workflows/steps.ts',
    ]),
    'suite-child': Object.freeze([
      'src/adapters/crossword-live-facts.ts',
      'src/adapters/default-specialized.ts',
      'src/adapters/generated-specialized.ts',
      'src/adapters/history-live-facts.ts',
      'src/adapters/image-live-facts.ts',
      'src/adapters/image-specialized.ts',
      'src/adapters/object-live-facts.ts',
      'src/adapters/object-specialized.ts',
      'src/adapters/registry.ts',
      'src/adapters/restore-live-facts.ts',
      'src/adapters/text-live-facts.ts',
      'src/adapters/text-specialized.ts',
      'src/allocation/allocate.ts',
      'src/allocation/lease.ts',
      'src/allocation/ownership.ts',
      'src/allocation/port-reservation.ts',
      'src/allocation/process-identity.ts',
      'src/allocation/reserve.ts',
      'src/browser/doctor.ts',
      'src/browser/guarded-setup.ts',
      'src/browser/launch.ts',
      'src/browser/primitives.ts',
      'src/browser/public-controls.ts',
      'src/browser/seam.ts',
      'src/canonical/canonicalize.ts',
      'src/canonical/identity.ts',
      'src/canonical/package8-identity.ts',
      'src/catalogue/correctness-compatibility.ts',
      'src/catalogue/correctness.ts',
      'src/catalogue/fingerprint.ts',
      'src/catalogue/fixtures.ts',
      'src/catalogue/load.ts',
      'src/catalogue/resolve.ts',
      'src/catalogue/resources.ts',
      'src/catalogue/suite.ts',
      'src/catalogue/wp5-compatibility-oracle.ts',
      'src/cleanup/cleanup.ts',
      'src/cli/diagnostic.ts',
      'src/cli/output.ts',
      'src/cli/suite.ts',
      'src/cli/termination-state.ts',
      'src/cli/termination.ts',
      'src/commands/command-context.ts',
      'src/commands/doctor-command-context.ts',
      'src/commands/production-absence-command-context.ts',
      'src/contracts/adapter.ts',
      'src/contracts/case-model.ts',
      'src/contracts/catalogues.ts',
      'src/contracts/command-check.ts',
      'src/contracts/correctness.ts',
      'src/contracts/coverage.ts',
      'src/contracts/crossword-observation.ts',
      'src/contracts/crossword.ts',
      'src/contracts/diagnostics.ts',
      'src/contracts/discriminants.ts',
      'src/contracts/evidence-transaction.ts',
      'src/contracts/execution.ts',
      'src/contracts/final-public-record.ts',
      'src/contracts/final-record-reader.ts',
      'src/contracts/final-record-v4.ts',
      'src/contracts/final-result-dto.ts',
      'src/contracts/final-suite-record.ts',
      'src/contracts/fixtures.ts',
      'src/contracts/geometry-v2.ts',
      'src/contracts/geometry-v3.ts',
      'src/contracts/history-observation.ts',
      'src/contracts/observation.ts',
      'src/contracts/planner-outputs.ts',
      'src/contracts/production-absence.ts',
      'src/contracts/raster.ts',
      'src/contracts/resources.ts',
      'src/contracts/restore-observation.ts',
      'src/contracts/result-agreement.ts',
      'src/contracts/runtime.ts',
      'src/contracts/schema-versions.ts',
      'src/contracts/seam.ts',
      'src/contracts/selection-clear.ts',
      'src/contracts/suite.ts',
      'src/contracts/wall-clock.ts',
      'src/contracts/workflows.ts',
      'src/coverage/account.ts',
      'src/coverage/load.ts',
      'src/coverage/resolve.ts',
      'src/coverage/select.ts',
      'src/coverage/validate.ts',
      'src/evidence/cleanup-authority.ts',
      'src/evidence/final-reader.ts',
      'src/evidence/final-suite-writer.ts',
      'src/evidence/final-writer.ts',
      'src/evidence/guard.ts',
      'src/evidence/private-snapshot.ts',
      'src/evidence/provenance-collector.ts',
      'src/evidence/provenance-component-policy.ts',
      'src/evidence/provenance.ts',
      'src/evidence/public-dto.ts',
      'src/evidence/publication.ts',
      'src/evidence/reference-graph.ts',
      'src/evidence/sanitize.ts',
      'src/evidence/semantic-digest.ts',
      'src/evidence/transaction.ts',
      'src/evidence/writer.ts',
      'src/kernels/crossword-kernel.ts',
      'src/kernels/history-kernel.ts',
      'src/kernels/image-kernel.ts',
      'src/kernels/nested-object-kernel.ts',
      'src/kernels/restore-kernel.ts',
      'src/kernels/text-kernel.ts',
      'src/oracles/crossword.ts',
      'src/oracles/evaluate.ts',
      'src/oracles/geometry.ts',
      'src/oracles/history.ts',
      'src/oracles/image.ts',
      'src/oracles/nested-object.ts',
      'src/oracles/profile-registry.ts',
      'src/oracles/restore.ts',
      'src/oracles/warped-text.ts',
      'src/orchestration/command-execution.ts',
      'src/orchestration/diagnostic-execution.ts',
      'src/orchestration/doctor-command-execution.ts',
      'src/orchestration/final-active-path.ts',
      'src/orchestration/production-absence-command-execution.ts',
      'src/orchestration/suite-execution.ts',
      'src/planner/compile-plan.ts',
      'src/planner/execution-materialization.ts',
      'src/planner/execution-support.ts',
      'src/planner/launchability.ts',
      'src/planner/materialize.ts',
      'src/planner/normalize-intent.ts',
      'src/planner/plan-case.ts',
      'src/planner/preflight.ts',
      'src/readiness/coherent-capture.ts',
      'src/readiness/correlated-gate.ts',
      'src/readiness/profile-registry.ts',
      'src/readiness/raster-currentness.ts',
      'src/registry/reconcile.ts',
      'src/registry/validate.ts',
      'src/resources/request-log.ts',
      'src/resources/resolve.ts',
      'src/resources/routes.ts',
      'src/routing/resolve.ts',
      'src/runtime/action-cycle.ts',
      'src/runtime/config-snapshot.ts',
      'src/runtime/environment-facts.ts',
      'src/runtime/environment.ts',
      'src/runtime/execute-crossword-plan.ts',
      'src/runtime/execute-history-plan.ts',
      'src/runtime/execute-image-plan.ts',
      'src/runtime/execute-plan.ts',
      'src/runtime/execute-restore-plan.ts',
      'src/runtime/launch.ts',
      'src/runtime/outcomes.ts',
      'src/runtime/paths.ts',
      'src/runtime/process-group.ts',
      'src/runtime/readiness.ts',
      'src/runtime/result-outcome.ts',
      'src/runtime/run-id.ts',
      'src/workflows/execute.ts',
      'src/workflows/steps.ts',
    ]),
  }),
});

export function getProvenanceComponentPolicy(): ProvenanceComponentPolicy {
  return PROVENANCE_COMPONENT_POLICY;
}

export function assertFinalProvenanceComponentPolicy(): void {
  if (!PROVENANCE_COMPONENT_POLICY.authoritativeForFinalProvenance) {
    throw new Error('The provenance component policy is not authoritative for final provenance.');
  }
}

export function canonicalComponentEntryRoots(component: ProvenanceFlow): readonly string[] {
  return Object.freeze([...PROVENANCE_ACTIVE_ENTRY_ROOTS[component]]);
}

export function frozenClosureForFlow(flow: ProvenanceFlow): readonly string[] {
  return PROVENANCE_COMPONENT_POLICY.frozenClosures[flow];
}

const COMPONENT_PATHS: Readonly<Record<ProvenanceComponentName, readonly string[]>> = Object.freeze(
  {
    cliBootstrapDigest: Object.freeze([
      'src/cli/diagnostic.ts',
      'src/cli/doctor.ts',
      'src/cli/output.ts',
      'src/cli/production-absence.ts',
      'src/cli/suite.ts',
      'src/cli/termination-state.ts',
      'src/cli/termination.ts',
    ]),
    runnerDigest: Object.freeze([]),
    evidenceWriterDigest: Object.freeze([
      'src/canonical/package8-identity.ts',
      'src/contracts/evidence-transaction.ts',
      'src/evidence/cleanup-authority.ts',
      'src/evidence/final-reader.ts',
      'src/evidence/final-suite-writer.ts',
      'src/evidence/final-writer.ts',
      'src/evidence/guard.ts',
      'src/evidence/private-snapshot.ts',
      'src/evidence/provenance-collector.ts',
      'src/evidence/provenance-component-policy.ts',
      'src/evidence/provenance.ts',
      'src/evidence/public-dto.ts',
      'src/evidence/publication.ts',
      'src/evidence/reference-graph.ts',
      'src/evidence/sanitize.ts',
      'src/evidence/semantic-digest.ts',
      'src/evidence/transaction.ts',
      'src/evidence/writer.ts',
    ]),
    verifierDigest: Object.freeze([
      'src/contracts/evidence-transaction.ts',
      'src/evidence/final-reader.ts',
      'src/evidence/guard.ts',
      'src/evidence/provenance-component-policy.ts',
      'src/evidence/publication.ts',
      'src/evidence/reference-graph.ts',
      'src/evidence/sanitize.ts',
      'src/evidence/transaction.ts',
    ]),
  },
);

/** Digest a canonical sorted closure; entries must already be read-only hashes. */
export function componentDigestFromEntries(
  entries: readonly GovernedPathEntry[],
  component: ProvenanceComponentName,
  flow: ProvenanceFlow = 'diagnostic',
): string {
  const allowed = new Set(
    component === 'runnerDigest' ? frozenClosureForFlow(flow) : COMPONENT_PATHS[component],
  );
  const selected = entries
    .filter((entry) => allowed.has(entry.path))
    .map((entry) => ({ path: entry.path, sha256: entry.sha256 }))
    .sort((left, right) => left.path.localeCompare(right.path));
  const expected = [...allowed].sort();
  if (
    selected.length !== expected.length ||
    selected.some((entry, index) => entry.path !== expected[index])
  ) {
    throw new Error(`Provenance component closure mismatch for ${component}/${flow}.`);
  }
  return sha256Hex(
    canonicalize({
      domain: `makeit:provenance-component:${component}:v${PROVENANCE_COMPONENT_POLICY_VERSION}`,
      entries: selected,
    }),
  );
}
